### ISSUE TITLE
Example: Passing geoJson data from the database and displaying it on the map

### ISSUE THREAD

**Issue by Otienoh** [iMuMz/NovaLeafletMap#1]
Hello,
Good job on the package.

In the usage section for the `GeoJSON` the example given is not clear on how it can be implemented using the package. Could you please show how we can load the geoJson data after fetching in from the database?

```php
LeafletMap::make('Map View') // Should the name correspond with the table column name?
->type('GeoJson')
->geoJson('') // Do you pass the field name here or son object?
->center('-6.081689','145.391881')
```

I hope you a clearer example is something you can share and will also help demonstrate how one can map multiple polygons on the map?

**Comment by iMuMz** [comment]
> Hello,
> Good job on the package.
> 
> In the usage section for the `GeoJSON` the example given is not clear on how it can be implemented using the package. Could you please show how we can load the geoJson data after fetching in from the database?
> 
> ```
> LeafletMap::make('Map View') // Should the name correspond with the table column name?
> ->type('GeoJson')
> ->geoJson('') // Do you pass the field name here or son object?
> ->center('-6.081689','145.391881')
> ```
> 
> I hope you a clearer example is something you can share and will also help demonstrate how one can map multiple polygons on the map?

Hi Otienoh,

You just have to pass valid GeoJSON to the geoJson method :

`->geoJson()`

Example :

`$myGeoJson = '{
            "type": "FeatureCollection",
            "features": [
              {
                "type": "Feature",
                "properties": {},
                "geometry": {
                  "type": "Polygon",
                  "coordinates": [
                    [
                      [
                        36.3592529296875,
                        1.6367402361776067
                      ],
                      [
                        35.9527587890625,
                        0.9997051308419692
                      ],
                      [
                        37.474365234375,
                        1.2303741774326145
                      ],
                      [
                        36.3592529296875,
                        1.6367402361776067
                      ]
                    ]
                  ]
                }
              }
            ]
          }'`

`LeafletMap::make('Map View')`
`->zoom(6)`
`->type('GeoJson')`
`->geoJson($myGeoJson)`
`->center('0.4836686','36.5191145')`

Output :

![Screenshot 2020-07-06 at 06 50 25](https://user-images.githubusercontent.com/22936672/86556946-04179080-bf55-11ea-9a04-81616d102406.png)

**Comment by Otienoh** [comment]
Ah thanks, it is clearer now. Here is how I implemented it if clear, I can polish it and create a PR to add it to the usage example section.

Add an attribute on your model to easily return the JSON data. You could add this to you Model class
```php
 public function getGeoJsonDataAttribute()
    {
       return is_null($this->geoJson)? null :collect($this->geoJson)->toJson();
    }
```

Then on your Nova resource add this i.e. you now have access to `$this->geoJsonData`
```php
    public function fields(Request $request)
    {
        return [
            ID::make()->onlyOnDetail(),
            ...
            Text::make(__('Name'), 'name')->sortable()->required(),
            new Panel('Location Details', $this->renderMap()),
        ];
    }

    /**
     * Leaflet field
     */
    protected function renderMap(): array
    {
        if (is_null($this->geoJsonData)) {
            return [];
        }

        return [
            LeafletMap::make('Map View')
                ->zoom(15)
                ->type('GeoJson')
                ->geoJson($this->geoJsonData)
                ->height('800px')
                ->center($this->center[0], $this->center[1])
                ->popupName('name')
                ->onlyOnDetail(),
        ];
    }
```


The only issue I have is the map renders far of from the actual polygon i.e. polygon coordinates draw the area in North America map renders in Asia.

Meaning users have to drag the map view to the polygon area. Any possible gotchas I might be missing? 
Thanks in Advance.

**Comment by iMuMz** [comment]
You can use the `->center()` and `->zoom()` methods to bound the map to your features
