### ISSUE TITLE
Popup bug on GeoJson type

### ISSUE THREAD

**Issue by gabrielesbaiz** [iMuMz/NovaLeafletMap#3]
Popup on GeoJson type doesn't seem to work properly and return undefined.

I think it's something on this line:
https://github.com/iMuMz/NovaLeafletMap/blob/e29d9bb9dbd401d13481f6547eee70e51f8042d4/resources/js/components/DetailField.vue#L196

**Comment by iMuMz** [comment]
What does your GeoJson look like?

Please see below an example

```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          221.48437499999997,
          61.438767493682825
        ]
      },
      "properties": {
        "popupTag": "Hello"
      }
    }
  ]
}
```

![Screenshot 2021-01-13 at 11 18 13](https://user-images.githubusercontent.com/22936672/104432246-7cf54600-5591-11eb-9a55-62aee8901398.png)

```php
LeafletMap::make('Map View','map')
            ->zoom(4)
            ->type('GeoJson')
            ->geoJson($this->geo_json)
            ->popupName('popupTag')
```

**Comment by gabrielesbaiz** [comment]
I've used the GeoJson Example code on documentation with:

```json
...
      "properties": {
        "popup": "I am a Popup"
      },
...
```
And LeafletMap without popupName:

```php
LeafletMap::make('Map View','map')
            ->zoom(4)
            ->type('GeoJson')
            ->geoJson($this->geo_json)
```

Now I've understand what `->popupName()` attribute means and how to use **with** `->type('GeoJson')`!
