### ISSUE TITLE
Automatic zoom level through fitBounds

### ISSUE THREAD

**Issue by JoanBonnin** [iMuMz/NovaLeafletMap#6]
Hi there! I'm starting to add this nice package (algonside with NoaLeafletCard) and I wonder if it could be possible to automatically set the appropiate zoom to fit the elements in the map.

It seems to be achievable through the [map fitBounds method](https://leafletjs.com/reference-1.7.1.html#map-fitbounds). Do you think this may be interesting to the package?

**Comment by iMuMz** [comment]
@JoanBonnin This has been added to the Nova 4 package and geojson will now automatically fit to the bounds of the map.
