### ISSUE TITLE
Not showed when on create, Nova 4

### ISSUE THREAD

**Issue by mialyGit** [iMuMz/NovaLeafletMap#7]
Hello
    I use Nova : "4.26.5" and Laravel 9 
   My streetMap fields don't show  when I do this :

```
    public function fields(NovaRequest $request)
    {
        return [ 
            LeafletMap::make('Map View')
        ];
    }
```
    
    I have no error from laravel but I have this in console of browser : 
    
    "Cannot read properties of undefined (reading '_c') at Proxy.render (leaflet-map:1:618369)"

**Comment by iMuMz** [comment]
A Nova 4 compatible package is now available

https://github.com/iMuMz/Nova4FieldMap
